PL/Controllers/AlumnoController.cs
using Microsoft.AspNetCore.Mvc;

namespace PL.Controllers
{
    public class AlumnoController : Controller
    {
        //Inyeccion de dependencias-- patron de diseño
        private readonly IConfiguration _configuration;
        private readonly Microsoft.AspNetCore.Hosting.IHostingEnvironment _hostingEnvironment;

        public AlumnoController(IConfiguration configuration, Microsoft.AspNetCore.Hosting.IHostingEnvironment hostingEnvironment)
        {
            _configuration = configuration;
            _hostingEnvironment = hostingEnvironment;
        }
        //exponer la logica de negocio a internet 
        //HTTP 
        //URL 
        [HttpGet]
        public ActionResult GetAll()
        {

            ML.Alumno alumno = new ML.Alumno();

            //alumno.Nombre = (alumno.Nombre == null) ? "" : alumno.Nombre;
            //alumno.ApellidoPaterno = (alumno.ApellidoPaterno == null) ? "" : alumno.ApellidoPaterno;
            //alumno.ApellidoMaterno = (alumno.ApellidoMaterno == null) ? "" : alumno.ApellidoMaterno;
            //ML.Result result = BL.Alumno.GetAll(alumno);

            //alumno.Alumnos = result.Objects;
            //return View(alumno);
            ML.Result result = new ML.Result();
            result.Objects = new List<object>();

            try
            {
                //SOAP 
                //REST (JSON) Serializacion y deserializacion Postman swagger(probar el endpoint, validarlo)
                //Probar(Consumo) web services : postman-swagger
                //Consumirlo en el proyecto : el controlador de MVC o AJAX 
                using (var client = new HttpClient())
                {
                    string urlApi = _configuration["urlApi"];
                    client.BaseAddress = new Uri(urlApi);

                    var responseTask = client.GetAsync("Alumno/GetAll");
                    responseTask.Wait();

                    var resultServicio = responseTask.Result;

                    if (resultServicio.IsSuccessStatusCode)
                    {
                        var readTask = resultServicio.Content.ReadAsAsync<ML.Result>();
                        readTask.Wait();

                        foreach (var resultItem in readTask.Result.Objects)
                        {
                            ML.Alumno resultItemList = Newtonsoft.Json.JsonConvert.DeserializeObject<ML.Alumno>(resultItem.ToString());
                            result.Objects.Add(resultItemList);
                        }
                    }
                    alumno.Alumnos = result.Objects;
                }

            }
            catch (Exception ex)
            {
            }

            return View(alumno);
        }

        [HttpGet]
        public ActionResult Form(int? idAlumno) //2
        {
            ML.Result resultSemestre = BL.Semestre.GetAll();
            ML.Result resultPlantel = BL.Plantel.GetAll();

            ML.Alumno alumno = new ML.Alumno();
            alumno.Semestre = new ML.Semestre();

            alumno.Horario = new ML.Horarios();
            alumno.Horario.Grupo = new ML.Grupo();
            alumno.Horario.Grupo.Plantel = new ML.Plantel();


            if (resultSemestre.Correct && resultPlantel.Correct)
            {
                alumno.Horario.Grupo.Plantel.Planteles = resultPlantel.Objects;
                alumno.Semestre.Semestres = resultSemestre.Objects;
            }
            if (idAlumno == null)
            {
                //add //formulario vacio
                return View(alumno);
            }
            else
            {
                //getById
                ML.Result result = BL.Alumno.GetById(idAlumno.Value); //2

                if (result.Correct)
                {
                    alumno = (ML.Alumno)result.Object;//unboxing
                    alumno.Semestre.Semestres = resultSemestre.Objects;

                    alumno.Horario = new ML.Horarios();
                    alumno.Horario.Grupo = new ML.Grupo();
                    alumno.Horario.Grupo.Plantel = new ML.Plantel();
                    alumno.Horario.Grupo.Plantel.Planteles = resultPlantel.Objects;
                    //update
                    return View(alumno);
                }
                else
                {
                    ViewBag.Message = "Ocurrio al consultar la información del alumno";
                    return View("Modal");
                }


            }


        }

        [HttpPost]
        public ActionResult Form(ML.Alumno alumno)
        {
            IFormFile file = Request.Form.Files["fuImage"];

            if (file != null)
            {
                byte[] imagen = ConvertToBytes(file);

                alumno.Imagen = Convert.ToBase64String(imagen);
            }
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(_configuration["urlApi"]);

                //HTTP POST
                var postTask = client.PostAsJsonAsync<ML.Alumno>("Alumno/Add",alumno );
                postTask.Wait();

                var result = postTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    ViewBag.Mensaje = "Se ha registrado el alumno";
                    return PartialView("Modal");
                }
                else
                {
                    ViewBag.Mensaje = "No se ha registrado el alumno";
                    return PartialView("Modal");
                }
            }
            //ML.Result result = new ML.Result();
            //if (ModelState.IsValid == true)
            //{
            //    if (alumno.IdAlumno == 0)
            //    {
            //        //add 
            //        result = BL.Alumno.Add(alumno);

            //        if (result.Correct)
            //        {
            //            ViewBag.Message = "Se completo el registro satisfactoriamente";
            //        }
            //        else
            //        {
            //            ViewBag.Message = "Ocurrio un error al insertar el registro";
            //        }

            //        return View("Modal");
            //    }
            //    else
            //    {

            //        //update
            //        //result = BL.Alumno.Add(alumno);

            //        //if (result.Correct)
            //        //{
            //        //    ViewBag.Message = "Se actualizo la información satisfactoriamente";
            //        //}
            //        //else
            //        //{
            //        //    ViewBag.Message = "Ocurrio un error al actualizar el registro";
            //        //}
            //        return View("Modal");
            //    }
            //}
            //else
            //{
            //    alumno.Semestre = new ML.Semestre();
            //    alumno.Horario = new ML.Horarios();
            //    alumno.Horario.Grupo = new ML.Grupo();
            //    alumno.Horario.Grupo.Plantel = new ML.Plantel();

            //    ML.Result resultSemestre = BL.Semestre.GetAll();
            //    ML.Result resultPlantel = BL.Plantel.GetAll();

            //    alumno.Semestre.Semestres = resultSemestre.Objects;
            //    alumno.Horario.Grupo.Plantel.Planteles = resultPlantel.Objects;
            //    return View(alumno);
            //}

        }

        [HttpGet]
        public ActionResult Delete(int idAlumno)
        {
            //ML.Result result = BL.Alumno.Delete(idAlumno);
            return View();
        }

        [HttpPost]
        public JsonResult GrupoGetByIdPlantel(int idPlantel)
        {
            ML.Result result = new ML.Result();
            result = BL.Grupo.GetByIdPlantel(idPlantel);

            return Json(result.Objects);
        }

        public static byte[] ConvertToBytes(IFormFile imagen)
        {

            using var fileStream = imagen.OpenReadStream();

            byte[] bytes = new byte[fileStream.Length];
            fileStream.Read(bytes, 0, (int)fileStream.Length);

            return bytes;
        }
        [HttpPost]
        public JsonResult CambiarStatus(int idAlumno, bool status)
        {
            ML.Result result = BL.Alumno.ChangeStatus(idAlumno, status);

            return Json(result);
        }
        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(string nombre, string apellido)
        {
            ML.Result result = BL.Alumno.GetByNombre(nombre);
            if (result.Correct)
            {
                ML.Alumno alumno = (ML.Alumno)result.Object;
                if (apellido == alumno.ApellidoPaterno)
                {
                    return View();
                }
                else
                {
                    ViewBag.Message = "La contraseña no coincide";
                    return PartialView("Modal");
                }
            }
            else
            {
                ViewBag.Messge = "El usuario no existe";
                return PartialView("Modal");
            }
        }
    }
}

PL/Views/Alumno/Form.cshtml
@model ML.Alumno
@{
    ViewBag.Title = "Form";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h2>Alumno</h2>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            @using (Html.BeginForm("Form", "Alumno", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                <div class="form-horizontal">
                    <div class="form-group">
                        <div class="col-md-3">
                            @Html.LabelFor(model => model.IdAlumno, new { @class = "visually-hidden" })

                            @Html.TextBoxFor(model => model.IdAlumno, new { @class = "visually-hidden form-control" })
                            @Html.ValidationMessageFor(model => model.IdAlumno)
                        </div>
                    </div>
                    <div class="row">

                        <div class="col-md-3">
                            @Html.LabelFor(model => model.Nombre)

                            @Html.TextBoxFor(model => model.Nombre, new { @class = "form-control", @id = "txtNombre", @onkeypress="SoloLetras(event, 'lblNombre', 'txtNombre')" })

                            @Html.ValidationMessageFor(model => model.Nombre)
                            @Html.Label(null, "", new {@id ="lblNombre"})
                        </div>

                        <div class="col-md-3">
                            @Html.LabelFor(model => model.ApellidoPaterno)
                            @Html.TextBoxFor(model => model.ApellidoPaterno, new { @class = "form-control", @id = "txtApellidoPaterno", @onkeypress="SoloLetras(event, 'lblApellidoPaterno', 'txtApellidoPaterno')" })
                            @Html.ValidationMessageFor(model => model.ApellidoPaterno)
                             @Html.Label(null, "", new {@id ="lblApellidoPaterno"})
                        </div>

                        <div class="col-md-3">
                            @Html.LabelFor(model => model.ApellidoMaterno)
                            @Html.TextBoxFor(model => model.ApellidoMaterno, new { @class = "form-control", @id = "txtApellidoMaterno" })
                            @Html.ValidationMessageFor(model => model.ApellidoMaterno)
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-3">
                            @Html.LabelFor(model => model.FechaNacimiento)
                            <div class="input-group">
                                <span class="input-group-text" id="basic-addon1"><i class="fa-solid fa-user-plus fa-fade" style="color:greenyellow"></i></span>
                                @*@Html.TextBoxFor(model => model.FechaNacimiento, new { @class = "form-control datefield", type = "date"})*@
                                @*@Html.TextBoxFor(model => model.FechaNacimiento, new { @class = "form-control", @id = "datepicker"})*@
                                @Html.TextBoxFor(model => model.FechaNacimiento, new { @class = "form-control", @id = "txtFechaNacimiento"})
                                @Html.ValidationMessageFor(model => model.FechaNacimiento)
                            </div>
                        </div>
                        <div class="col-md-3">
                            @Html.LabelFor(model => model.Horario.Turno)
                            <div class="input-group">
                                <span class="input-group-addon" id="basic-addon1"><i class="fa-solid fa-user-plus fa-fade" style="color:greenyellow"></i></span>
                                @Html.TextBoxFor(model => model.Horario.Turno, new { @class = "form-control", @id = "txtApellidoMaterno" })
                                @Html.ValidationMessageFor(model => model.Horario.Turno)
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-3">
                            @Html.LabelFor(model => model.Semestre)
                            @Html.DropDownListFor(model => model.Semestre.IdSemestre, new SelectList(Model.Semestre.Semestres, "IdSemestre", "Nombre"), "Selecciona un semestre correspondiente", new { @class = "form-control" })
                        </div>
                        <div class="col-md-3">
                            @Html.LabelFor(model => model.Horario.Grupo.Plantel)
                            @Html.DropDownListFor(model => model.Horario.Grupo.Plantel.IdPlantel, new SelectList(Model.Horario.Grupo.Plantel.Planteles, "IdPlantel", "Nombre"), "Selecciona un plantel", new { @class = "form-control", @id = "ddlPlantel" })
                        </div>
                        @if (Model.Horario.Grupo.Grupos != null)
                        {
                            <div class="col-md-3">
                                @Html.LabelFor(model => model.Horario.Grupo)
                                @Html.DropDownListFor(model => model.Horario.Grupo.IdGrupo, new SelectList(Model.Horario.Grupo.Grupos, "IdGrupo", "Nombre"), "Selecciona un Grupo", new { @class = "form-control", @id = "ddlGrupo" })
                            </div>
                        }
                        else
                        {
                            <div class="col-md-3">
                                @Html.LabelFor(model => model.Horario.Grupo)
                                @Html.DropDownListFor(model => model.Horario.Grupo.IdGrupo, new SelectList(string.Empty, "Value", "Text"), "Selecciona un Grupo", new { @class = "form-control", @id = "ddlGrupo" })
                            </div>
                        }

                        <div class="input-group-addon mb-3">
                            <span class="input-group-text" id="basic-addon1"><i class="fa-solid fa-user-plus"></i></span>
                            <input id="fuImage" type='file' class="form-control" name="fuImage" onchange="validateFile(this), readURL(this);  " />
                        </div>


                        @if (Model.Imagen != null)
                        {

                            <img id="Img" src="data:image/*;base64,@Convert.FromBase64String(Model.Imagen)" style="width:250px ; height:250px" />

                        }
                        else
                        {
                            <img id="Img" src="~/Imagenes/SinImagen.png" style="width:250px ; height:250px" />
                        }
                    </div>



                    <div class="form-group">
                        <div class="col-md-3">
                            <input type="submit" value="Guardar" class="btn btn-success" />
                            @Html.ActionLink("Regresar", "GetAll", "Alumno", htmlAttributes: new { @class = "btn btn-danger" })
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

@section Scripts {
<link rel="stylesheet" href="//code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">
<link rel="stylesheet" href="/resources/demos/style.css">
<script src="https://code.jquery.com/jquery-3.6.0.js"></script>
<script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>

<script type="text/javascript">
           $(document).ready(function () {
               $("#ddlPlantel").change(function () {
                   $("#ddlGrupo").empty();
                   $.ajax({
                       type: 'POST',
                       url: '@Url.Action("GrupoGetByIdPlantel")',
                       dataType: 'json',
                       data: { idPlantel: $("#ddlPlantel").val() },
                       success: function (grupos) {
                           $("#ddlGrupo").append('<option value="0">' + 'Seleccione una opción' + '</option>');
                           $.each(grupos, function (i, grupos) {
                               $("#ddlGrupo").append('<option value="'
                                   + grupos.idGrupo + '">'
                                   + grupos.nombre + '</option>');
                           });
                       },
                       error: function (ex) {
                           alert('Failed.' + ex);
                       }
                   });
               });
           });

           function validateFile() {
               var allowedExtension = ['jpeg', 'jpg', 'png'];
               var fileExtension = document.getElementById('fuImage').value.split('.').pop().toLowerCase();
               var isValidFile = false;
               for (var index in allowedExtension) {
                   if (fileExtension === allowedExtension[index]) {
                       isValidFile = true;
                       break;
                   }
               }
               if (!isValidFile) {
                   alert('Las extensiones permitidas son : *.' + allowedExtension.join(', *.'));
                   document.getElementById('fuImage').value = ""
               }
               return isValidFile;
           }

           function readURL(input) {
               if (input.files && input.files[0]) {
                   var reader = new FileReader();
                   reader.onload = function (e) {
                       $('#Img').attr('src', e.target.result);
                   };
                   reader.readAsDataURL(input.files[0]);
               }
           }

           //$(function () {
           //    $("#datepicker").datepicker();
           //    $("#format").on("change", function () {
           //        $("#datepicker").datepicker("option", "dateFormat", $(this).val());
           //    });
           //});

           $(function () {
               $("#txtFechaNacimiento").datepicker({
                   dateFormat: 'dd-mm-yy',
                   changeMonth: true,
                   changeYear: true
               });
           });
    function SoloLetras(e, idLabel, idTextbox) {
           var caracter = e.key;
           if (!/^[a-zA-Z]/g.test(caracter)) {
               $('#' + idLabel ).text("Solo se aceptan letras");
               $('#' + idLabel).css({ "color": "red" });
               $('#' + idTextbox).css({ "border-color": "red", "background-color": "#f8d7da" });
               return false;
           }
           else {
               $('#' + controlId).text("");
               $('#' + idTextbox).css({ "border-color": "green"});
               return true;
           }
            }




</script>
}

PL/Views/Alumno/GetAll.cshtml
@model ML.Alumno
@{
    ViewBag.Title = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">
    <div class="row">
        <h2>Alumno</h2>
    </div>
    <hr />
    <div class="row">
        <div style="float:right">
            @Html.ActionLink("+", "Form", "Alumno", htmlAttributes: new { @class = "btn btn-success" })
        </div>
    </div>
    <hr />
    <div class="row">
        @if (Model.Alumnos != null)
        {
            <table class="table table-dark table-bordered table-responsive table-hover" id="tblAlumno">
                <thead>
                    <tr >
                        <td class="text-center" style=" font-weight:bold;">Editar</td>

                        <td class="d-none">IdAlumno</td>
                        <td class="text-center" style=" font-weight:bold;">Nombre</td>
                        <td class="text-center" style=" font-weight:bold;">Fecha Nacimiento</td>
                        <td class="text-center" style=" font-weight:bold;">Semestre</td>
                        <td class="text-center" style=" font-weight:bold;">Imagen</td>
                        <td class="text-center" style=" font-weight:bold;">Status</td>

                        <td class="text-center" style=" font-weight:bold;">Eliminar</td>
                    </tr>
                </thead>

                <tbody>
                    @foreach (ML.Alumno alumno in Model.Alumnos)
                    {
                        <tr>
                            <td class="text-center"><a class="btn btn-warning" id="prueba" onmouseover="Animar()" href="@Url.Action("Form", "Alumno", new { IdAlumno = alumno.IdAlumno })"><i class="bi bi-pencil-square fa-beat" style="color: ghostwhite;"></i> </a></td>

                            <td class="d-none">@alumno.IdAlumno</td>
                            <td>@alumno.Nombre @alumno.ApellidoPaterno @alumno.ApellidoMaterno</td>
                            <td>@alumno.FechaNacimiento</td>
                            <td>@alumno.Semestre.Nombre</td>
                            <td>
                                @if (alumno.Imagen != null && alumno.Imagen != "")
                                {

                                    <img id="Img" src="data:image/*;base64,@alumno.Imagen" style="width:250px ; height:250px" />

                                }
                                else
                                {
                                    <img id="Img" src="~/Imagenes/SinImagen.png" style="width:100px ; height:100px; text-align: center; vertical-align: middle;" />
                                }
                            </td>
                            @if (alumno.Status)
                            {
                                <td style="text-align: center; vertical-align: middle;">
                                    <div class="form-check form-switch">
                                        <input class="form-check-input" type="checkbox" id="flexSwitchCheckDefault" checked onchange="ChangeStatus(@alumno.IdAlumno, this)">
                                    </div>
                                </td>
                            }
                            else
                            {
                                <td style="text-align: center; vertical-align: middle;">
                                    <div class="form-check form-switch">
                                        <input class="form-check-input" type="checkbox" id="flexSwitchCheckDefault" onchange="ChangeStatus(@alumno.IdAlumno, this);">
                                    </div>
                                </td>
                            }



                            <td class="text-center"><a class="btn btn-danger glyphicon glyphicon-erase" href="@Url.Action("Delete", "Alumno", new { IdAlumno = alumno.IdAlumno })" onclick="return confirm('Estas seguro que deseas eliminar este registro?');"></a></td>
                        </tr>
                    }
                </tbody>
            </table>


        }
        else
        {
            <div class="alert alert-danger" role="alert">Ocurrio un error al realizar la consulta </div>
        }
    </div>
</div>

@section Scripts {
<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.13.1/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.13.1/js/dataTables.material.min.js"></script>
<script src="https://cdn.datatables.net/1.13.1/js/dataTables.bootstrap5.min.js"></script>

<script type="text/javascript">
    $(document).ready(function () {
        $('#tblAlumno').DataTable({
            searching: false,
            "lengthMenu": [[2, 10, 15, 20, -1], [5, 10, 15, 20, "All"]],
            autoWidth: false,
            columnDefs: [
                {
                    targets: ['_all'],
                    className: 'mdc-data-table__cell',
                },
            ],
            language: {
                url: "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json",
            },
         });
    });

        function ChangeStatus(idAlumno,e){
        var status = e.checked
         $.ajax({
                type: 'POST',
                url: '@Url.Action("CambiarStatus")',
                dataType: 'json',
                data: {idAlumno, status},
                success: {               },
                error: function (ex) {
                    alert('Failed.' + ex);
                }
            });
    }

    $(document).ready(function Animar(){
        $('#prueba').hover(function(){
            $('#prueba').addClass('fa-beat');
        },
        function(){
            $('#prueba').removeClass('fa-beat');
        });
    });
</script>
}

PL/Views/Alumno/Login.cshtml
@model ML.Alumno
@{
    ViewData["Title"] = "Login";
    Layout = null;
}
<head>
    <link rel="stylesheet" href="~/css/Login.css" />
</head>

<div class="container">
    <div class="screen">
        <div class="screen__content">
            @using (Html.BeginForm("Login", "Alumno", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
            <form class="login">
                <div class="login__field">
                    <i class="login__icon fas fa-user"></i>
                    @Html.TextBoxFor(model => model.Nombre, new { @class = "login__input", @placeholder ="User name / Email" })
                </div>
                <div class="login__field">
                    <i class="login__icon fas fa-lock"></i>
                    <input type="password" class="login__input" placeholder="Password" name="apellido">
                </div>
                <button class="button login__submit" type="submit">
                    <span class="button__text">Log In Now</span>
                    <i class="button__icon fas fa-chevron-right"></i>
                </button>
            </form>
            }
            <div class="social-login">
                <h3>log in via</h3>
                <div class="social-icons">
                    <a href="#" class="social-login__icon fab fa-instagram"></a>
                    <a href="#" class="social-login__icon fab fa-facebook"></a>
                    <a href="#" class="social-login__icon fab fa-twitter"></a>
                </div>
            </div>
        </div>
        <div class="screen__background">
            <span class="screen__background__shape screen__background__shape4"></span>
            <span class="screen__background__shape screen__background__shape3"></span>
            <span class="screen__background__shape screen__background__shape2"></span>
            <span class="screen__background__shape screen__background__shape1"></span>
        </div>
    </div>
</div>

PL/Views/Alumno/Modal.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div class="modal" tabindex="-1" role="dialog" id="modalValidacion">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Aviso</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>@ViewBag.Message</h5>
            </div>
            <div class="modal-footer">
                @Html.ActionLink("Regresar", "GetAll", "Alumno", htmlAttributes: new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
</div>

<script>
    $('#modalValidacion').modal();
</script>